### ISSUE TITLE
Remove Appveyor and Travis CI from required pipeline steps

### ISSUE THREAD

**Issue by mrmodise** [strongloop/loopback4-example-shopping#1001]
We have successfully configured Github actions for our CI process. However, builds are failing due to Appveyor and Travis CI. Additionally, we would like to set all the Github actions steps as required for any PR to land

**Comment by bajtos** [comment]
Thank you @mrmodise for opening this follow-up issue for your PR https://github.com/strongloop/loopback4-example-shopping/pull/998 that configured GitHub actions.

I edited required checks for `master` branch - removed Travis CI and AppVeoyor, added GHA-powered checks. I also removed webhooks that were triggering AppVeyor and Travis CI builds.

I see that you have already removed `.travis.yml` and `appveyor.yml` files, so I think all should be good now?

Please let me know if there is anything else remaining to do, or close this issue as done if not.

**Comment by mrmodise** [comment]
Thanks all good

**Comment by bajtos** [comment]
On the second thought, would you @mrmodise like to update README and replace the badge pointing to Travis CI with a badge for GitHub Actions? See line 3 in https://github.com/strongloop/loopback4-example-shopping/blob/master/README.md

```md
[![Travis Build Status](https://travis-ci.com/strongloop/loopback4-example-shopping.svg?branch=master)](https://travis-ci.com/strongloop/loopback4-example-shopping)
```

GitHub Actions badge to use:

```md
![Continous Integration](https://github.com/strongloop/loopback4-example-shopping/workflows/Continous%20Integration/badge.svg)
```

Preview: 
![Continous Integration](https://github.com/strongloop/loopback4-example-shopping/workflows/Continous%20Integration/badge.svg)
