### ISSUE TITLE
Replace Express implementation on recommendation server with LoopBack style implementation of the same

### ISSUE THREAD

**Issue by mrmodise** [strongloop/loopback4-example-shopping#1003]
LoopBack now supports using Express middleware inside of a LoopBack application. Would be nice to demonstrate this use case here rather than use pure Express implementation

@raymondfeng @hacksparrow @jannyHou your thoughts?

**Comment by hacksparrow** [comment]
I am fine with keeping it as such, as an example of integrating LoopBack with a non-LoopBack backend.
