### ISSUE TITLE
Login issue: different user can use the same email.

### ISSUE THREAD

**Issue by gobackhuoxing** [strongloop/loopback4-example-shopping#103]
I can create different users with the same email. Because users are using email for login, that could be a problem.

Example:
I create two users with the same email but different password:
```
{
    "email": "duplicate@gmail.com",
    "password": "test123456",
    "firstname": "t1",
    "surname": "t1"
}

{
    "email": "duplicate@gmail.com",
    "password": "test1234567",
    "firstname": "t2",
    "surname": "t2"
}
```

Then I can only login as the first user. If I try the second user's password, I get UnauthorizedError:

```
{
    "error": {
        "statusCode": 401,
        "name": "UnauthorizedError",
        "message": "The credentials are not correct."
    }
}
```
The second user can never login.

**Comment by dhmlau** [comment]
@b-admike, I'm assigning this to you since you're looking into it.

**Comment by dougal83** [comment]
@gobackhuoxing You would probably be advised to make email unique on the [user model](https://github.com/strongloop/loopback4-example-shopping/blob/1ec2d9166d813ac771fa14920553daae8bc71455/packages/shopping/src/models/user.model.ts#L17) (add unique: true,).  The create user function on the user controller will throw a constraint error on duplicate email and you'll not have the highlighted issue.
