### ISSUE TITLE
Integration of the user authentification not replicable

### ISSUE THREAD

**Issue by Shadsa** [strongloop/loopback4-example-shopping#157]
Hi Loopback team,

We are working on an API using the LB4 version, and we are working on an LDAP authentication. I already see that no LDAP packages are up, so I'm trying to build a work around based on the JWT auth show in this example. 

So far the integration work perfectly, since I just have to copy a bunch of services, auth-strats, and the user model/controller (I'm skipping the repo, since I'm using an ldap service instead).

Our architecture is the liking : 

![image](https://user-images.githubusercontent.com/12796289/59280794-72145a00-8c66-11e9-8645-e72d592b9a62.png)

I already have cleanup the user-service, deleting all the DB stuff, and replacing by a call to the LDAP service (a bunch of code not integrated with the inject system of loopback).

But, when editing the app file, I'm facing a strange error, and I can't find a workaround. It seemes linked to the binding mechanism and Context, but I can't figure much more.

The error is the following :

Argument of type 'this' is not assignable to parameter of type 'Context'.
  Type 'LbcoreApplication' is missing the following properties from type 'Context': configResolver, configure, getConfigAsValueOrPromise, setupConfigurationResolverIfNeeded, and 3 more.ts(2345)

Here a screenshot of the line : 

![image](https://user-images.githubusercontent.com/12796289/59281243-38901e80-8c67-11e9-8ae7-c5187341d434.png)

and there for the full code : 

```
import {BootMixin} from '@loopback/boot';
import {ApplicationConfig, BindingKey} from '@loopback/core';
import {
  RestExplorerBindings,
  RestExplorerComponent,
} from '@loopback/rest-explorer';
import {RepositoryMixin} from '@loopback/repository';
import {RestApplication} from '@loopback/rest';
import {ServiceMixin} from '@loopback/service-proxy';
import * as path from 'path';
import {MySequence} from './sequence';
import {
  TokenServiceBindings,
  UserServiceBindings,
  TokenServiceConstants,
} from './keys';
import {JWTService} from './services/jwt-service';
import {MyUserService} from './services/user-service';
import {
  AuthenticationComponent,
  registerAuthenticationStrategy,
} from '@loopback/authentication';
import {PasswordHasherBindings} from './keys';
import {BcryptHasher} from './services/hash.password.bcryptjs';
import {JWTAuthenticationStrategy} from './authentication-strategies/jwt-strategy';

export interface PackageInfo {
  name: string;
  version: string;
  description: string;
}
export const PackageKey = BindingKey.create<PackageInfo>('application.package');

const pkg: PackageInfo = require('../package.json');

export class LbcoreApplication extends BootMixin(
  ServiceMixin(RepositoryMixin(RestApplication)),
) {
  constructor(options?: ApplicationConfig) {
    super(options);
    this.setUpBindings();

    // Bind authentication component related elements
    this.component(AuthenticationComponent);

    registerAuthenticationStrategy(this,JWTAuthenticationStrategy); => Here is the line causing drama

    // Set up the custom sequence
    this.sequence(MySequence);

    // Set up default home page
    this.static('/', path.join(__dirname, '../public'));

    // Customize @loopback/rest-explorer configuration here
    this.bind(RestExplorerBindings.CONFIG).to({
      path: '/explorer',
    });
   
    this.component(RestExplorerComponent);

    this.projectRoot = __dirname;
    // Customize @loopback/boot Booter Conventions here
    this.bootOptions = {
      controllers: {
        // Customize ControllerBooter Conventions here
        dirs: ['controllers'],
        extensions: ['.controller.js'],
        nested: true,
      },
    };
  }
  setUpBindings(): void {
    // Bind package.json to the application context
    this.bind(PackageKey).to(pkg);
    this.bind(TokenServiceBindings.TOKEN_SECRET).to(
      TokenServiceConstants.TOKEN_SECRET_VALUE,
    );

    this.bind(TokenServiceBindings.TOKEN_EXPIRES_IN).to(
      TokenServiceConstants.TOKEN_EXPIRES_IN_VALUE,
    );

    this.bind(TokenServiceBindings.TOKEN_SERVICE).toClass(JWTService);

    // // Bind bcrypt hash services
    this.bind(PasswordHasherBindings.ROUNDS).to(10);
    this.bind(PasswordHasherBindings.PASSWORD_HASHER).toClass(BcryptHasher);

    this.bind(UserServiceBindings.USER_SERVICE).toClass(MyUserService);
  }
}
```

I can provide modified file such as user-service if needed, I don't put them here right now, the post is already pretty long.

Basicly, it's exactly the same code as your example, and I really can't figure what's going on.

Kind regards,
Shad

**Comment by emonddr** [comment]
@Shadsa ,

I ran into the ` 'this' is not assignable to parameter of type 'Context'.` problem one day (before this application was complete, and before updates to @loopback/authentication was officially released) and I was using the `npm link` command to link to create links from the shopping application dependencies to a different directory containing the latest code for the authentication package. 
I wasn't doing it right, and basically two different @loopback/authentication modules were being loaded...which confused vscode.

Try : `npm run build:full`, and see what errors the build brings up. 

This is how I discovered the cause of my problem.

**Comment by emonddr** [comment]
Be sure to grab the latest @loopback/authentication package.

**Comment by Shadsa** [comment]
@emonddr Thanks for your tip, I will give it a try. As information, we have commented this line of code, and the application seems running perfectly fine, with a fully functional LDAP authentication. So I'm really curious about it function : What does this line do exactly ??

**Comment by Shadsa** [comment]
The` npm run build` throw me another stuff while building the app.

![image](https://user-images.githubusercontent.com/12796289/59416702-32fd1a80-8dc6-11e9-9dfc-8e23dfd60827.png)

So far, the app still work despite this error (and work perfectly, no error at all). This error start showing sudenly, despite the fact that this code was not touch for a month, and with no error at all at this moment.

Does an update of the filter spec have break something ?

**Comment by Shadsa** [comment]
Okay, so I have successfully patch all this stuff, and here is the result :

- My original issue with the line was fixed by @emonddr 's solution. Thank you !
- The second issue can be fix with a force-cast in the .find, like this : .find(<Filter>land>>filter).
 But I can make a proper Land Filter, or I cannot access nested properties of the Land.

**Comment by emonddr** [comment]
> My original issue with the line was fixed by @emonddr 's solution. Thank you !

:)
