### ISSUE TITLE
Update package.json and package-lock.json to remove passport references

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback4-example-shopping#175]
This application depends on @loopback/authentication package.

Just recently, the passport adapter was moved into its own package : @loopback/authentication-passport  .

All references to passport in @loopback/authentication was recently removed in PR 
https://github.com/strongloop/loopback-next/pull/3224 . Once this change is released, then this shopping cart example's package.json and package-lock.json needs to be updated to new version numbers, and needs to remove all 'passport' references.

Related to recent work done for a passport adapter : https://github.com/strongloop/loopback-next/issues/2311

## Acceptance Criteria
- [ ] mocha tests run after package.json and package-lock.json have been cleaned

**Comment by emonddr** [comment]
https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/package-lock.json

```
...
"@loopback/authentication": {
			"version": "2.1.2",
			"resolved": "https://registry.npmjs.org/@loopback/authentication/-/authentication-2.1.2.tgz",
			"integrity": "sha512-qvUtSCgX8aWyybdRCoQyo27Yk682yTTJq2MZrGp4kMXG6yPx2weY4ONmKcWkGmUH7EhzEyQhiR6d9Lvnwj8KGw==",
			"requires": {
				"@loopback/context": "^1.19.1",
				"@loopback/core": "^1.8.2",
				"@loopback/metadata": "^1.2.2",
				"@loopback/openapi-v3": "^1.6.2",
				"@loopback/rest": "^1.16.0",
				"@types/express": "^4.17.0",
				"passport": "^0.4.0",
				"passport-strategy": "^1.0.0"
			}
		},
...
```

**Comment by emonddr** [comment]
In  https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/package.json

we need to remove

```
 "dependencies": {
...
    "@types/passport": "1.0.0",
...
  },
```

**Comment by dhmlau** [comment]
Putting the estimate as 1 because the effort is small and it's more time consuming to go through the estimation process. :)

**Comment by dhmlau** [comment]
@emonddr, is this done?  I saw the PR #191 has merged. Thanks.

**Comment by emonddr** [comment]
> @emonddr, is this done? I saw the PR #191 has merged. Thanks.

yes it is done. thx. :)
