### ISSUE TITLE
Advanced version of shopping app with each component as microservices

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback4-example-shopping#22]
## Background
The repo https://github.com/strongloop/loopback4-example-microservices was initially created to illustrate how microservices can be created using LoopBack 4. 

Over time, this repo was not keeping up on the changes as we've moving along.  As a result, it needs to be updated in order to be running again.  Another problem with this repo is that it was created while we're settling on the architecture/design.

@strongloop/sq-lb-apex @raymondfeng were discussing what is the best way to handle it.  Below is the proposal.

## Description
Based on what we have in this example-shopping application, we create an "advanced" version of the app, so that each component is a microservice.  All the components will still be in the same repository as monorepo.

## Acceptance Criteria
- [ ] Create a new repo (monorepo) for this microservice version of the shopping app.  
   - Make each component as microservice
   - Document the steps as "how to" documentation page
- [x] Deprecate https://github.com/strongloop/loopback4-example-microservices and indicate the new repo created above should be the one to reference.

**Comment by raymondfeng** [comment]
I have deprecated https://github.com/strongloop/loopback4-example-microservices
