### ISSUE TITLE
Error: Cannot find module 'C:\node_modules\npm\bin\npm-cli.js'

### ISSUE THREAD

**Issue by MAHOSSAN** [strongloop/loopback4-example-shopping#235]
I download this project and tried to run it but i am getting following errors ..
C:\Users\Khundokar Nirjor\Desktop\loop4\loopback4-example-shopping> npm start

> loopback4-example-shopping-monorepo@1.0.0 prestart C:\Users\Khundokar Nirjor\Desktop\loop4\loopback4-example-shopping
> npm run build

> loopback4-example-shopping-monorepo@1.0.0 build C:\Users\Khundokar Nirjor\Desktop\loop4\loopback4-example-shopping
> lerna run build

internal/modules/cjs/loader.js:628
    throw err;
    ^
Error: Cannot find module 'C:\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopback4-example-shopping-monorepo@1.0.0 build: `lerna run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopback4-example-shopping-monorepo@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Khundokar Nirjor\AppData\Roaming\npm-cache\_logs\2019-08-10T02_05_39_890Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopback4-example-shopping-monorepo@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopback4-example-shopping-monorepo@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Khundokar Nirjor\AppData\Roaming\npm-cache\_logs\2019-08-10T02_05_40_026Z-debug.log

**Comment by dhmlau** [comment]
@MAHOSSAN, I followed the instruction in the `Installation` section to install dependencies and start the application and it seems to be working fine.  Here is what i did:
```
 git clone https://github.com/strongloop/loopback4-example-shopping.git
cd loopback4-example-shopping
npm i
npm start 
```

Looking at your error, I found this thread https://github.com/nodejs/help/issues/1618 that might be able to help you. At the end of the discussion, someone says:
> Updating to the latest version of NPM fixed it for me. npm install npm@latest -g

So you might want to give it a try.

**Comment by MAHOSSAN** [comment]
for me its not working

**Comment by dhmlau** [comment]
are you using `nvm` to install Node.js?  If not, we'd recommend you to do so to isolate some of the environment issues.

**Comment by hardikbodar** [comment]
i will some error i am trying to solve but note solve this error please help us...
C:\Users\SARKAR>npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\SARKAR\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\SARKAR\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SARKAR\AppData\Roaming\npm-cache\_logs\2019-11-18T11_19_29_089Z-debug.log

C:\Users\SARKAR>expo init App
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Users\SARKAR\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)←[39m
←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)←[39m
←[90m    at internal/main/run_main_module.js:17:11←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by dhmlau** [comment]
It's been 4 months since the last comment. There have been quite a lot of changes in this repo.  
- the structure of the repo has changed. Here is the instruction to set up and run: https://github.com/strongloop/loopback4-example-shopping#installation.
- there's some fixes around running command on Windows. See discussion https://github.com/strongloop/loopback-next/issues/4425. 

I'd like to close this issue.  Please open a new issue if you still are running into problems. Thanks.

**Comment by anuragyadav-ab** [comment]
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\ANURAG\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
please help showing error while creating a project

**Comment by dougal83** [comment]
Hi @anuragyadav-ab

I cannot find any issue with cloning this project and running `npm i`, `npm run docker:start` and `npm run start`.  All work as expected.

Please create a new issue and give step by step instruction on how to replicate your problem.

**Comment by richawasp** [comment]
Hi tried everything but i still giving the same error and the strange part is i have able to launch appium from administrator without any issue but when i try to run from another user which has admin rights giving me an error each time .this is so frustrating ERROR cannot find module main.js  at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
Can anyone suggest how to run appium setup successfully i installed node.js and then checked version of npm aand node which worked fine when i tried running npm install -g appium m getting error and unable to install appium successfully.

**Comment by dougal83** [comment]
Hi @richawasp, I'm not sure how your post relates to this repo.  The error here is generic, perhaps you should look for assistance in a Nodejs or 'appium' forum?

**Comment by gangadharsm** [comment]
I got same error, update the node js and angular cli, then this issue is resolved for me.

**Comment by BhagyaLahiru** [comment]
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by anjusm1** [comment]
Error: Cannot find module 'C:\Project\app.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
  throw err;  ^

Error: Cannot find module 'C:\Project\app.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
