### ISSUE TITLE
User model setting to make the email unique is not working

### ISSUE THREAD

**Issue by nflaig** [strongloop/loopback4-example-shopping#236]
## Description
The email address should be unique for each user which ought to be enforced by [user model setting](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/models/user.model.ts#L10). However, it is possible for me to create multiple users with the same email address. I also noticed this issue with another LB 4 application I am currently developing. Another point to add is that I did not have this issue with an older instance of my database, only after deleting the old one and creating a new one the issue happened which makes me think a newer version of a LB 4 dependency might cause this issue.

## Steps to Reproduce
1. Start the application with `npm start`
2. `curl -X POST "http://localhost:3000/users" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"email\":\"user@domain.com\",\"password\":\"password\"}"`
3. `curl -X POST "http://localhost:3000/users" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"email\":\"user@domain.com\",\"password\":\"password\"}"`

## Current Behavior
Step 3 returns HTTP status code `200` and two users with the same email address are created.

![image](https://user-images.githubusercontent.com/38436224/62830773-61f00b00-bc14-11e9-8306-a46bc2e37639.png)

## Expected Behavior
Step 3 returns HTTP status code `409` and the error message `Email value is already taken` ,according to [user.controller.ts](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/controllers/user.controller.ts#L78).

## Environment
- Windows 10 Version 1803 (Build 17134.885)
- Node.js v8.11.4
- MongoDB v4.0.9
- Node module versions according to [package.json](https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/package.json#L44)

## Acceptance Criteria
- [x] It should not be possible to create two users with the same email address

**Comment by dhmlau** [comment]
@jannyHou, could you please take a look? Thanks.

**Comment by zzhenryquezz** [comment]
I change this line in the user controller and work normaly this way, i don't know if is because i using postgres but the error code was diferent and don't have the field errmss so the if state it was never true

```
try {
     
      const user = await this.userRepository.create(user)

      return user;

    } catch (error) {
      console.log(error)
      if (error.code === '23505' && error.detail.includes('email') && error.detail.includes('already exists')) {
        throw new HttpErrors.Conflict('Email value is already taken');
      } else {
        throw error;
      }
    }
```

**Comment by nflaig** [comment]
@zzhenryquezz yes, it is a mongodb specific error it won't work with any other database and currently also not with mongodb as it seems.

**Comment by nflaig** [comment]
@dhmlau Any progress on this?

**Comment by dougal83** [comment]
@nflaig Hi Nico, can you confirm that you ran the [migrate script](https://github.com/strongloop/loopback4-example-shopping/blob/428b828a4ad3e47803260ac14264fe6bff97847f/packages/shopping/package.json#L20) on the new db to create the unique index?

**Comment by nflaig** [comment]
Hi @dougal83,
this seems to fix the issue, thanks. Interesting that no one of the loopback team suggested that.
It is also never mentioned in the readme, so I am wondering where/when this should be run. Doing it manually every time you install the code on a new systems seems wrong maybe it could be put into src/index.ts

**Comment by dougal83** [comment]
> Interesting that no one of the loopback team suggested that.

They are extremely busy.  TBH, I should have spotted this 23 days ago! :)

I recommend that you familiarise yourself with the [migration documentation](https://loopback.io/doc/en/lb4/Database-migrations.html).  Perhaps you could suggest an improvement to this example repos documentation to help others that miss the migration aspect?  I added the script but never thought to add a note.

**Comment by nflaig** [comment]
To be honest I haven't thought of migration at all to solve this issue because if you use mongoose for example the unique key property just works without it. Another thing is that it worked for me in the past then suddenly stopped working so I thought a dependency update caused the issue. 

Since the script is needed for lb4 applications, I would suggest the approach to [auto-update on start](https://loopback.io/doc/en/lb4/Database-migrations.html#auto-update-database-at-start) or as another workaround run it after `npm run build` and before `npm start`.
