### ISSUE TITLE
VS Code Debugger

### ISSUE THREAD

**Issue by MemoryChips** [strongloop/loopback4-example-shopping#28]
# VS Code Debugger Launch Task

Please add a launch.json file with a configured launch task to run the vs code debugger.

**Comment by dhmlau** [comment]
@MemoryChips, would you be interested in submitting a PR?

**Comment by jannyHou** [comment]
@MemoryChips Something I tried before, may not work out-of-box, feel free to start with it:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha Tests",
      "program": "${workspaceFolder}/node_modules/@loopback/build/bin/run-mocha.js",
      "cwd": "${workspaceRoot}",
      "args": [
        "--recursive",
        "--require",
        "source-map-support/register",
        "--allow-console-logs",
        "dist/test/**/*.js"
      ]
    }
  ]
}
```

I can help you debug and land the PR.

**Comment by raymondfeng** [comment]
@MemoryChips Please follow instructions at https://code.visualstudio.com/docs/editor/debugging

**Comment by raymondfeng** [comment]
Go to `Debug --> Add configurations` will generate the following `launch.json`:
```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/index.js"
    }
  ]
}
```

And it works out of box. Feel free to open an PR.

**Comment by bajtos** [comment]
As for debugging tests, you must invoke `_mocha`, not any wrapper (`run-mocha`, `mocha`, etc.)

Alternatively, maybe you can use our `lb-mocha` wrapper if you add `--inspect` or `--inspect-brk` to the arguments? IDK.

@boneskull could you please help us? What is the recommended VSCode configuration for debugging Mocha tests?

**Comment by boneskull** [comment]
It's whatever VSCode gives you by default. I think it's called "Node.js: Mocha Tests" when adding to the array in `launch.json` (not sure if it comes from an extension, or which one).

```json
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha Tests",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
        "-u",
        "tdd",
        "--timeout",
        "999999",
        "--colors",
        "${workspaceFolder}/test"
      ],
      "internalConsoleOptions": "openOnSessionStart"
    }
```

**Comment by boneskull** [comment]
(the `--timeout 999999` is due to a bug in some versions of Mocha, which is fixed in v6; use `--no-timeout` or `-t 0` etc. instead)

**Comment by mathiasarens** [comment]
@boneskull Ok it works with ${workspaceFolder}/**dist**/test in my configuration. 

1. Is there a 'watch' command? I guess you have to run an 'npm build' to get your source code changes.
2. How does the configuration look like if you want to debug a single test case?  "${workspaceFolder}/dist/${relativeFile}" gives you the *.ts file and not the *.js file.

**Comment by jannyHou** [comment]
I believe it's been added in https://github.com/strongloop/loopback4-example-shopping/pull/29. 
Closing the issue. Feel free to open it if you still have questions. Thanks.
