### ISSUE TITLE
mongo url parser fails

### ISSUE THREAD

**Issue by MemoryChips** [strongloop/loopback4-example-shopping#30]
When I try to use a mongo url of the form
```js
mongodb+srv://<USER>:<PASSWORD>@<MY_ATLAS_CONNECTION>/test?retryWrites=true
```
the url parser fails and returns a url object of null. The above format is what mongo Atlas uses to connect to their mongo servers. This error crashes the server. The error occurs whether I escape the characters in the url or not. I am able to connect using my url in my other programs.

```json
{
  "name": "mongo",
  "connector": "mongodb",
  "url": "mongodb+srv://<USER>:<PASSWORD>@<MY_ATLAS_CONNECTION>/test?retryWrites=true",
  "database": "test",
  "useNewUrlParser": true
}
```

Please fix this or verify that your url parser works correctly.

**Comment by dhmlau** [comment]
@MemoryChips, I believe this is related to this on-going PR: https://github.com/strongloop/loopback-connector-mongodb/pull/497.

**Comment by dhmlau** [comment]
@MemoryChips, we've landed the community PR for adding support for `mongodb+srv`. See PR
https://github.com/strongloop/loopback-connector-mongodb/pull/497
As a result, I'm going to close this issue as resolved.  Thanks.
