### ISSUE TITLE
user-service error in "securityId" 

### ISSUE THREAD

**Issue by FSalazarH** [strongloop/loopback4-example-shopping#362]
Hi guys, I'm trying to implementate this approach in my own application follow the documentation [here](https://loopback.io/doc/en/lb4/Authentication-Tutorial.html#contributions), so, I'd one error and I don't know why:

In `src/services/user-service.ts:52:13`:

`error TS2418: Type of computed property's value is 'string | undefined', which is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

52     return {[securityId]: user.id, name: userName};
               ~~~~~~~~~~~~

  node_modules/@loopback/security/dist/types.d.ts:12:5
    12     [securityId]: string;
           ~~~~~~~~~~~~
    The expected type comes from property 'unique symbol' which is declared here on type 'UserProfile'`

Thanks in advance!

**Comment by FSalazarH** [comment]
> Hi guys, I'm trying to implementate this approach in my own application follow the documentation [here](https://loopback.io/doc/en/lb4/Authentication-Tutorial.html#contributions), so, I'd one error and I don't know why:
> 
> In `src/services/user-service.ts:52:13`:
> 
> `error TS2418: Type of computed property's value is 'string | undefined', which is not assignable to type 'string'.
> Type 'undefined' is not assignable to type 'string'.
> 
> 52 return {[securityId]: user.id, name: userName};
> ~~~~~~~~~~~~
> 
> node_modules/@loopback/security/dist/types.d.ts:12:5
> 12 [securityId]: string;
> ~~~~~~~~~~~~
> The expected type comes from property 'unique symbol' which is declared here on type 'UserProfile'`
> 
> Thanks in advance!

## Edit: 
The error was origin in User Model, in parameter `id`, lb4 as default set the attribute `id?`, which can be undefined or not. So, we ensure that the `id` don't have the option to be undefined, this is donde removing the `?`.

**Comment by elloGuy69** [comment]
This really helped with the headache I was having since I couldn't figure out this weird error. Thank you.
