### ISSUE TITLE
Mismatch between node/npm/grpc versions 

### ISSUE THREAD

**Issue by bizbi** [strongloop/loopback4-example-shopping#371]
The application fails to build, with what is apparently a mismatch between node/npm/grpc versions - see below.  What are the recommended versions to use, please?

1986 verbose node v13.1.0
1987 verbose npm  v6.13.0
1988 error code ELIFECYCLE
1989 error errno 1
1990 error grpc@1.21.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
1990 error Exit status 1
1991 error Failed at the grpc@1.21.1 install script.

**Comment by raymondfeng** [comment]
Please use node 12 or 10 instead of 13

**Comment by bizbi** [comment]
@raymondfeng thanks, this worked - closing issue
