### ISSUE TITLE
@hasmany parameter not showing in explorer in new version

### ISSUE THREAD

**Issue by techaks** [strongloop/loopback4-example-shopping#38]
check 

> user.model.ts

there is parameter   
```
@hasMany(() => Order)
  orders: Order[];
```

in previous i was able to see in explorer screen but now AFTER UPDATE  IN new version i am not able to see it what is solution to show this

**Comment by techaks** [comment]
@jannyHou i have solved this issue 

```
@property.array(() => Order)
@hasMany(() => Order)
  orders: Order[];
```

can u help me in MongoDB aggregation on Loopback 4?

**Comment by b-admike** [comment]
Yes that is correct, we've removed the `property.array()` call from the `hasMany` decorator in https://github.com/strongloop/loopback-next/pull/2178. Would it help others if we documented this change in behaviour?

**Comment by techaks** [comment]
Yes will help alot to others. Please help me in mongodb aggregation.
