### ISSUE TITLE
Email and Password Validation 

### ISSUE THREAD

**Issue by psaunders** [strongloop/loopback4-example-shopping#39]
This would be the perfect place to show people how to validate inputs using the methods that are hinted at in the documentation here: https://loopback.io/doc/en/lb4/Parsing-requests.html#request-body

> Please refer to the documentation on @requestBody decorator to get a comprehensive idea of defining custom validation rules for your models.

As the flagship example of the framework it doesn't look good having a bunch of old school if statements in the controller method doing validation. Someone who knows what they are doing could easily setup a "minimum length" example for the password which would help a lot.

**Comment by jannyHou** [comment]
@psaunders 👍 Good catch.

**Comment by jannyHou** [comment]
Acceptance Criteria:

- [ ]  Validate password by specifying `minLengh` property for `password` , see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#properties
- [ ] Validate email by specifying `format: email` for `email`, see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object-examples

**Comment by psaunders** [comment]
Yeah you can put this in, but you end up with something pretty huge like this which is what we ended up with:

```ts
  @post('/accounts', {
    responses: {
      '200': {
        description: 'Account model instance',
        content: { 'application/json': { schema: { 'x-ts-type': Account } } },
      },
    },
  })
  async create(@requestBody({
      content: {
        'application/json': {
          schema: {
            required: ['email', 'password'],
            properties: {
              email: {
                type: 'string',
                format: 'email',
              },
              password: {
                type: 'string',
                pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*])(?=.{5,512})',
                minLength: 8,
                maxLength: 512,
                not: {
                  enum: list,
                },
              },
            },
          },
        },
      },
    }) accountRequest: Account): Promise<Account> {
    if (!accountRequest.email || !accountRequest.password) { // Needed as the validator doesn't pass on the required nature of these
      throw new HttpErrors.UnprocessableEntity();
    }
    return this.accountService.createWithEmail(accountRequest.email!, accountRequest.password!); // Must be non-null due to validation
  }
```

It would be good if there was:
1. All the validation stuff added to the object so you could have this in your object class:
```
@property({
    type: 'string',
    minLength:8,
    pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*])(?=.{5,512})',
    maxLength: 512
})
password?: string;
```
2. An actual request DTO for account (not an account model) because the account model has got (Kind of) validation stuff on it. Seems like having the model performing this role (Kind of) makes it not a great Entity or a great validator. It would be cool if you guys scaffolded out the creation of a request or validation system with your CLI after creating a model.

Let me know if I'm mistaken in these things not existing.

**Comment by jannyHou** [comment]
@psaunders 

```js
@property({
    type: 'string',
    minLength:8,
    pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*])(?=.{5,512})',
    maxLength: 512
})
password?: string;
```

is exactly what you could do, check the [API doc for decorator requestBody here](https://github.com/strongloop/loopback-next/blob/master/packages/openapi-v3/src/decorators/request-body.decorator.ts#L20-L79) the decorator infers the property spec when you specify `Account` as the type of your `accountRequest` :)

**Comment by psaunders** [comment]
Sorry, I am just not finding that to be the case.

https://github.com/psaunders/loopback4-example-shopping/commit/447388d1dc6037758106595ced7fe054b9ee2df5

I swapped the validation out to being on the model and it has no problems with saving non-email addresses and short passwords

**Comment by dhmlau** [comment]
PR #67 has landed. Closing as resolved.

**Comment by Arathy-sivan** [comment]
Hi,
How to 'verify an email' before  registering a user using loopback 4 ?

**Comment by hacksparrow** [comment]
@Arathy-sivan There are many different ways to achieve that, here's the high level instruction for one:

1. Create an endpoint (eg: `/verify-email`) using a controller for email verification. 
2. Create a unique unpredictable hash associated with the user.
3. Email the verification link to the user. `http://example.com/verify-email?hash=2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824&user=3474`
4. When a request is made to `/verify-email`, the email verification controller method then confirms the user with id `3474` has the hash `2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824`. Thereby, confirming the user actually received the email containing the link and clicked on it, thus making the email verified.

**Comment by BIMMITHA-GB** [comment]
I'm new to loopback 4, I have created an api to register the user. But now, I wanted to check whether the email is existing or not and valid ,before the successful registration. How can I resolve it?
Please provide any code for it.

**Comment by hacksparrow** [comment]
@BIMMITHA-GB you can enforce patter matching in your model property definition as shown in this example https://github.com/strongloop/loopback-next/blob/validation2/docs/site/Validation-REST-layer.md#example3-pattern-in-a-string.

**Comment by Arathy-sivan** [comment]
> @Arathy-sivan There are many different ways to achieve that, here's the high level instruction for one:
> 
> 1. Create an endpoint (eg: `/verify-email`) using a controller for email verification.
> 2. Create a unique unpredictable hash associated with the user.
> 3. Email the verification link to the user. `http://example.com/verify-email?hash=2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824&user=3474`
> 4. When a request is made to `/verify-email`, the email verification controller method then confirms the user with id `3474` has the hash `2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824`. Thereby, confirming the user actually received the email containing the link and clicked on it, thus making the email verified.

Could you please provide the code...

**Comment by BIMMITHA-GB** [comment]
> @BIMMITHA-GB you can enforce patter matching in your model property definition as shown in this example https://github.com/strongloop/loopback-next/blob/validation2/docs/site/Validation-REST-layer.md#example3-pattern-in-a-string.

Thank you for your response, I have checked the entered email is in valid format or not ,and also it exist in MySQL database or not. Now I need to verify the email address . Is there any code available in loopback4?

**Comment by hacksparrow** [comment]
@BIMMITHA-GB I have shared the high level instruction for doing that in https://github.com/strongloop/loopback4-example-shopping/issues/39#issuecomment-598677958.

**Comment by wa1one** [comment]
@hacksparrow  he asked for validation of an email before sign up, and not about verification of email box. This is very basic. Why you didn't implement validation?
