### ISSUE TITLE
Refactor this example to a monorepo

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback4-example-shopping#42]
### Description

Had a talk with Raymond on https://github.com/strongloop/loopback4-example-shopping/pull/41#discussion_r254339700 and come up with some ideas to restructure this example.

Here is a few points to consider, if team is good with it then we can turn them into acceptance criteria:

- Turn the example into a monorepo
- Switch to the new conversion of test folder `src/__tests__/`
- Import artifacts from root level path, see discussion in https://github.com/strongloop/loopback4-example-shopping/pull/41#discussion_r254339700
- Investigate a better file structure for advanced loopback app that combined with express or other middleware, reference project could be found in https://github.com/strongloop/loopback-next/issues/1982#issuecomment-457849492

**Comment by dhmlau** [comment]
This repo is now a monorepo. Closing it as done.
