### ISSUE TITLE
user-order.controller.ts doesn't auth with @authenticate('jwt') 

### ISSUE THREAD

**Issue by lygstate** [strongloop/loopback4-example-shopping#43]
user-order.controller.ts doesn't auth with @authenticate('jwt'),
besides, doesn't check the userId 
```
    if (userId !== currentUser.id) {
      throw new HttpErrors.BadRequest(
        `User id does not match: ${userId} !== ${currentUser.id}`,
      );
    }
```

**Comment by jannyHou** [comment]
@lygstate 

```
if (userId !== currentUser.id) {
      throw new HttpErrors.BadRequest(
        `User id does not match: ${userId} !== ${currentUser.id}`,
      );
    }
```
This is an authorization scenario which we are planning to implement after building the fundamental extensible authentication system.

**Comment by lygstate** [comment]
@jannyHou Sounds great, what's I can help.

**Comment by jannyHou** [comment]
@lygstate Thank you for being interested to help!

The story that tracks this change is https://github.com/strongloop/loopback-next/issues/1998, we are planning to add some abstractions in `@loopback/authentication` module then refactor this example repo to leverage them. 
I will let you know if we decide story#1998 can start with the refactor in parallel or before it. And we can help you work on the PR that enable the auth for orders.

**Comment by bajtos** [comment]
Before the work on the actual authorization is started, perhaps @lygstate can contribute the authentication changes we left out of February milestone? Cross-posting from https://github.com/strongloop/loopback-next/issues/1998:

> Rework `UserOrderController` to obtain the customer id from the request (the access token provided by the client) instead of a URL-path parameter.
> 
> For example, we can remove `/users/{userId}` prefix from all endpoints to end up with the following API:
>
> - `POST /orders` creates a new order
> - `GET /orders` returns all orders of the current user
> - `PATCH /orders?where=` to update some of the orders of the current user. I think this endpoint does not make sense in a Shopping app and should be eventually removed.
> - `DELETE /orders?where=` to delete some of the orders of the current user. I think this endpoint should be eventually removed, because orders are never deleted, they can be only closed (e.g. as cancelled).
>
> Existing REST API exposed by `UserController` should remain unauthenticated (allowing anonymous access).

**Comment by jannyHou** [comment]
@bajtos Yeah sounds good 👍 
Hi @lygstate would you be interested to submit a PR according to the description cross posted in https://github.com/strongloop/loopback4-example-shopping/issues/43#issuecomment-468311127?

**Comment by austin047** [comment]
Hello, I am new to loopback4 and github in general. 
I have basic knowledge on nodejs and express, i will like to work on this issue. I will be glad if i can get some hints on where to start.

**Comment by bajtos** [comment]
Hi @austin047, it's great to hear you are interested in helping out!

We have a detailed guide showing how to fork loopback-next repository on GitHub, create a feature branch, etc. see https://loopback.io/doc/en/lb4/submitting_a_pr.html

As for this particular task, you will need to make changes in the following files:
- [src/controllers/user-order.controller.ts](https://github.com/strongloop/loopback4-example-shopping/blob/master/src/controllers/user-order.controller.ts) - the implementation
- [test/acceptance/user-order.controller.acceptance.ts](https://github.com/strongloop/loopback4-example-shopping/blob/master/test/acceptance/user-order.controller.acceptance.ts) - the tests

Good luck 🍀

**Comment by austin047** [comment]
Thanks.

**Comment by dhmlau** [comment]
Closing as fixed.
