### ISSUE TITLE
Authentication and Authorization clean up

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback4-example-shopping#432]
The authentication and authorization example in the code is confusing and leads to many questions. Update the example to:

- [x] Get rid of CASBIN and show a custom implementation of authorization rules
- [x] Use the user id as the unique identifier while enforcing authorization 
- [x] Update the corresponding tests

---
ORIGINAL DESCRIPTION

In the discussion with @emonddr, it seems like we don't have a seamless flow for getting users authenticated and such users (with the same userid) are being authorized for certain actions. 

## Proposal 
At the high level, we should support the following scenarios, reusing our fictitious users `Alice` and `Bob` as listed in https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/fixtures/casbin/rbac_policy.csv:
- [x] Login as a regular user `Alice`, she can find and create orders. 
- [x] Login as a customer service rep `Bob`, he can find, create and delete orders
- [x] Login as a customer service supervisor `Clara`, she can find, create, update, patch and delete orders

Besides the pre-existing users, the shopping app allows to sign up as a customer.  The person then will have the same access as `Alice` (the regular user).

@emonddr, please chime in if I miss anything. Thanks. 

## Acceptance Criteria
- [ ] The CASBIN CSV file should contain a better  `user identifier` than : bob, alice . Perhaps the email?
- [ ] All authorizers use a consistent way of figuring out what user we are dealing with. Is it 'id` or `name` or `email` field. Does it make sense they don't use the same field to reject or allow access? If so, document clearly why this is so.
- [ ] Each authenticated user can only perform the actions on the resources for which they are authorized. This needs to be tested manually in API Explorer, and via mocha tests.

**Comment by emonddr** [comment]
The current obstacle is that the current shopping example app uses a specific user model
https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/models/user.model.ts#L24 
which has id, firstName,lastName, email, password etc.

The user logs in with email id and password.  So the uniqueness of user is determined by email.


Before a JWT token is created, we convert a User to UserProfile

https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/services/user-service.ts#L51 


```
convertToUserProfile(user: User): UserProfile {
    // since first name and lastName are optional, no error is thrown if not provided
    let userName = '';
    if (user.firstName) userName = `${user.firstName}`;
    if (user.lastName)
      userName = user.firstName
        ? `${userName} ${user.lastName}`
        : `${user.lastName}`;
    return {[securityId]: user.id, name: userName, id: user.id};
  }
```

then the token service creates a token based on UserProfile
but another type is actually created instead 

https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/services/jwt-service.ts#L54 

```
    const userInfoForToken = {
      id: userProfile[securityId],
      name: userProfile.name,
      email: userProfile.email,
    };
```
at this point, user profile has no email field, so this will be blank (so this area needs cleanup)

When 

The packages/shopping/fixtures/casbin/rbac_policy.csv  file assigns permissions to bob and alice.
But what are bob and alice?  The unique id? It should be email , right?

and finally this compare authorizer

https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/services/id.compare.authorizor.ts#L40

takes the userId from  /users/{userId}/orders  

which is a database unique id, and compares it to the id in the user profile which is a database id , but
the permissions in csv file is for 'bob'. 

This is probably not working.

**Comment by emonddr** [comment]
The authorization mocha tests use different user objects 

https://github.com/strongloop/loopback4-example-shopping/blob/99dee871fdb3a7077142d1f8b9ee7aa92f4a773e/packages/shopping/src/__tests__/acceptance/authorization.acceptance.ts#L19 

```
let userData = {
    email: 'testAuthor@loopback.io',
    firstName: 'customer_service',
  };

```

than

the authentication tests 

https://github.com/strongloop/loopback4-example-shopping/blob/99dee871fdb3a7077142d1f8b9ee7aa92f4a773e/packages/shopping/src/__tests__/acceptance/authentication.acceptance.ts#L26

```
const userData = {
    email: 'unittest@loopback.io',
    firstName: 'unit',
    lastName: 'test',
  };
```
It would be best if they were consistent.

**Comment by dhmlau** [comment]
Discussed with @bajtos, we think this should be done before we start adding the frontend.

**Comment by dhmlau** [comment]
Authorization clean up PR: https://github.com/strongloop/loopback4-example-shopping/pull/502

**Comment by hacksparrow** [comment]
Fixed via https://github.com/strongloop/loopback4-example-shopping/pull/502
