### ISSUE TITLE
Shopping App Website: View products

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback4-example-shopping#439]
Part of https://github.com/strongloop/loopback4-example-shopping/issues/425.

**Acceptance Criteria**

- [x] Basic infrastructure of the web site
- [x] 15 pre-populated products
- [x] Show products on landing page
- [x] Click on a product to see the details

**Comment by dhmlau** [comment]
Since this is already part of PR https://github.com/strongloop/loopback4-example-shopping/pull/468, I'm including this in `2020Q1`.

**Comment by dhmlau** [comment]
@hacksparrow, since PR https://github.com/strongloop/loopback4-example-shopping/pull/468 has landed, I believe this issue is done? If yes, could you please close it. Thanks.

**Comment by dhmlau** [comment]
Closing as done.
