### ISSUE TITLE
How to find user information with order 

### ISSUE THREAD

**Issue by techaks** [strongloop/loopback4-example-shopping#44]
I want to data like below: --

 

```
 [{
   userId:'akash',
   userName:'akash55',
   orders:[
      {
         orderId:1        
         product:{
            productId:1,
            producdName:'example'
         }
      }
   ]
}, 

{
   userId:'akash',
   userName:'akash55',
   orders:[
      {
         orderId:1        
         product:{
            productId:1,
            producdName:'example'
         }
      }
   ]
}
]
```

**Comment by techaks** [comment]
@dhmlau  help needed

**Comment by techaks** [comment]
@rmg   @klassicd  @makara @rpeterson  help needed

**Comment by techaks** [comment]
@dhmlau help please

**Comment by raymondfeng** [comment]
LoopBack 3.x has the `include` option for `filter` to do what you want. It's not available in LoopBack 4 yet. A workaround is to implement it in the controller similar as https://github.com/strongloop/loopback4-example-shopping/blob/master/src/controllers/user-order.controller.ts#L51.

**Comment by bajtos** [comment]
Please follow the discussion in https://github.com/strongloop/loopback-next/issues/1352 for updates about our progress on implementing native support for this feature.
