### ISSUE TITLE
Failure in the login process

### ISSUE THREAD

**Issue by baltameme** [strongloop/loopback4-example-shopping#451]
I am trying to run the sample project, where I made a successful registration for new user:
{
  "email": "user1@example.com",
  "password": "thel0ngp@55w0rd",
  "firstName": "User",
  "lastName": "One"
}

but when I try to login with the credentials of the same user i get the error on below:

{
  "error": {
    "statusCode": 401,
    "name": "UnauthorizedError",
    "message": "Invalid email or password."
  }
}

what can be the cause of this issue?

**Comment by dougal83** [comment]
Hey @baltameme 

I've just tried your example and can confirm that the example code behaves as expect for me.  Could you double check on your end in case it was a typo?

````json
{
  "email": "user1@example.com",
  "password": "thel0ngp@55w0rd"
}
````

Tested:
````curl
curl -X POST "http://localhost:3000/users/login" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"email\":\"user1@example.com\",\"password\":\"thel0ngp@55w0rd\"}"
````
Response: (200 OK)
````json
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMDVmNGZmOGE4ZWJjNDA0MDFlZjU1NiIsIm5hbWUiOiJVc2VyIE9uZSIsImlhdCI6MTU3NzQ0ODgyNywiZXhwIjoxNTc3NDQ5NDI3fQ.acT_C_A1UmgYz4kEhe6qR-EfdW1YoVvtyWS7ysPvtHs"
}
````

**Comment by baltameme** [comment]
Hi @dougal83 
Thanks for your reply.

I verified it again the repo is also on the master branch. what i have noticed as a pattern is that if i try those credentials:
{
  "email": "user1@example.com",
  "password": "thel0ngp@55w0rd"
}

then it does not work but if i submit another sample credentials like this one, then it works smoothly:
{
  "email": "basel@example.com",
  "password": "12345678"
}

**Comment by dougal83** [comment]
Hey @baltameme, I suppose the next step is to clear your database and try again.

**Comment by hacksparrow** [comment]
This is caused by a bug in the official MongoDB connector, they run `encodeURIComponent` on the credentials, but don't run `decodeURIComponent` before sending them to the database server. For now, just avoid special characters like `@`.
