### ISSUE TITLE
Shopping App Website: CRUD operation on shopping carts

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback4-example-shopping#475]
Part of https://github.com/strongloop/loopback4-example-shopping/issues/425.

**Acceptance Criteria**

- [x] Create new shopping cart
- [x] Update shopping cart
- [x] Delete shopping cart

**Comment by dhmlau** [comment]
Since this is already part of PR https://github.com/strongloop/loopback4-example-shopping/pull/468, I'm including this in `2020Q1`.

**Comment by dhmlau** [comment]
Closing as done.
