### ISSUE TITLE
Shopping App Website: UI testing

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback4-example-shopping#476]
Automated UI testing (https://webdriver.io/ or https://www.cypress.io).

**Acceptance Criteria**

All aspects of the UI interaction and behavior should be covered by a UI testing framework.

**Comment by mrmodise** [comment]
@hacksparrow am interested in working on this. Please advise on next steps.

**Comment by hacksparrow** [comment]
@mrmodise basically, we will have to ensure the UI - its appearance and interaction aspect - are working as expected and are not broken by accidental changes.

For eg: if the text was changed to "Lg in" from "Log In", it should be detected; clicking the "Log In" button should log in the user (since the form in pre-filled with working creds); trying to log in with wrong creds should not show the logged in UI, etc.

https://www.cypress.io/ or https://webdriver.io/ should help with it.

**Comment by mrmodise** [comment]
Thanks @hacksparrow I have used both and I would recommend Cypress. I can get started right away if you cool with it

**Comment by hacksparrow** [comment]
@mrmodise that would be great.

**Comment by mrmodise** [comment]
> @mrmodise that would be great.

Cool will send something your way ASAP

**Comment by dougal83** [comment]
+1 for Cypress.  Thank you @mrmodise

**Comment by mrmodise** [comment]
> +1 for Cypress. Thank you @mrmodise

@dougal83 they're coming up really well. Branch: https://github.com/mrmodise/loopback4-example-shopping/tree/feature/automated-ui-tests/packages/shopping/cypress/integration
