### ISSUE TITLE
Shopping App Website: Installation/setup documentation

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback4-example-shopping#477]
Document clearly how to set up the system and start the app running.
Currently the instructions in the [Installation] section is missing info to get the app up and running.

**Acceptance Criteria**

Should have enough information on getting the app to start successfully. 
It needs to include:
- [x] info to get mongodb and redis docker images up and running 
- [x] any other step to get things up and running (i.e. `npm start` without any issue)
- [x] add info in the frontend web site (probably just the web site link and a screen shot of the app)

**Comment by emonddr** [comment]
The `Try it out` section of [here](https://loopback.io/doc/en/lb4/Authentication-Tutorial.html#try-it-out) explains how to get the dbs running and how to add users, how to get a jwt token for one user, and how to use this token to access an authenticated endpoint.

So the instructions are not missing, they just aren't in the readme, although there is a link in the readme to the document url I mention above.

But yes, more needs to be added to instructions on how to use this shopping example with respect to authorization and the new ui.

**Comment by hacksparrow** [comment]
Closed via https://github.com/strongloop/loopback4-example-shopping/pull/528.
