### ISSUE TITLE
Add function in user service for adding new users

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback4-example-shopping#480]
Quoting @bajtos https://github.com/strongloop/loopback4-example-shopping/pull/468#discussion_r365295449:

> I am seeing this code pattern duplicated in quite few places now - in our controllers, acceptance tests and now in the migration script too.

> IMO, it's time to enhance our user service and add a function for adding new users, one that can be used from all places. It's out of scope of this pull request, but please consider adding this task on your checklist.

**Comment by mrmodise** [comment]
I will like to work on this. Thanks
