### ISSUE TITLE
not running docker => mongo and redis OK  

### ISSUE THREAD

**Issue by mersahin** [strongloop/loopback4-example-shopping#551]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start:app' ]
2 info using npm@6.13.7
3 info using node@v10.14.1
4 verbose run-script [ 'prestart:app', 'start:app', 'poststart:app' ]
5 info lifecycle loopback4-example-shopping-monorepo@1.1.1~prestart:app: loopback4-example-shopping-monorepo@1.1.1
6 info lifecycle loopback4-example-shopping-monorepo@1.1.1~start:app: loopback4-example-shopping-monorepo@1.1.1
7 verbose lifecycle loopback4-example-shopping-monorepo@1.1.1~start:app: unsafe-perm in lifecycle true
8 verbose lifecycle loopback4-example-shopping-monorepo@1.1.1~start:app: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user/Desktop/dir/loopback4-example-shopping/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/mysql/bin:/Users/user/Library/Android/sdk/platform-tools/
9 verbose lifecycle loopback4-example-shopping-monorepo@1.1.1~start:app: CWD: /Users/user/Desktop/dir/loopback4-example-shopping
10 silly lifecycle loopback4-example-shopping-monorepo@1.1.1~start:app: Args: [ '-c', 'node ./packages/shopping' ]
11 silly lifecycle loopback4-example-shopping-monorepo@1.1.1~start:app: Returned: code: 1  signal: null
12 info lifecycle loopback4-example-shopping-monorepo@1.1.1~start:app: Failed to exec start:app script
13 verbose stack Error: loopback4-example-shopping-monorepo@1.1.1 start:app: `node ./packages/shopping`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid loopback4-example-shopping-monorepo@1.1.1
15 verbose cwd /Users/user/Desktop/dir/loopback4-example-shopping
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:app"
18 verbose node v10.14.1
19 verbose npm  v6.13.7
20 error code ELIFECYCLE
21 error errno 1
22 error loopback4-example-shopping-monorepo@1.1.1 start:app: `node ./packages/shopping`
22 error Exit status 1
23 error Failed at the loopback4-example-shopping-monorepo@1.1.1 start:app script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dhmlau** [comment]
@mersahin, could you please provide more information on how you're starting the app?

**Comment by mersahin** [comment]
I found the solution.
I'm using macOS.
It worked after deleting Docker's certificates and recreating them.
