### ISSUE TITLE
Remove path parameter {userid} from order endpoints

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback4-example-shopping#629]
A follow up story from PR https://github.com/strongloop/loopback4-example-shopping/pull/71

Appreciate @austin047's effort on kicking off the refactor in the original PR and thank you @dougal83 for moving forward on it.

Acceptance Criteria:

- [ ] For endpoints defined in user-ordrer.controller.ts, remove the `{userid}` path parameter, infer the user from user profile(if exists) directly.
- [ ] Update corresponding tests.

cc @dougal83

**Comment by dougal83** [comment]
@jannyHou for this scenario are we assuming only the user can act on their own behalf?  Regarding best practice... If say, we had an admin acting on their behalf (manually update user order) then we would use endpoints as they are now or would we create separate endpoints for each role? Just curious about how we would go about a different scenario. As this shopping app does not have the admin role to perform such updates then the simplification is fine.

**Comment by dougal83** [comment]
@jannyHou The current authorization implementation is [checking the route for resource ownership](https://github.com/strongloop/loopback4-example-shopping/blob/9444829d109b8e6fbbcb216540e7a2cab7d91585/packages/shopping/src/services/basic.authorizor.ts#L63):

````ts
  if (currentUser[securityId] === authorizationCtx.invocationContext.args[0]) {
````
Therefore I don't believe this issue is workable without readdressing resource ownership in the basic authorisation implementation.  Please close this issue if you agree that the issue here is currently unecessary.

**Comment by jannyHou** [comment]
Hey @dougal83 sorry for late replying, recently I am cleaning up the tech debts and making a plan for improvements, which may affect this issue, so we haven't added the criteria for this issue.

Your concern is valid, 
```ts
if (currentUser[securityId] === authorizationCtx.invocationContext.args[0]) { }
```
assumes the path contains the id.

Taking `{id}` out of the path is a UX requirement created very long time ago, while we keep adding auth features in this repo it may doesn't fit the example anymore. And good catch for its conflict with authorization 👍 

I am closing it. We can reuse this issue if still want to refactor the path.
And @dougal83 thank you so much for the patience and all the suggestions 👍
