### ISSUE TITLE
Move test files to `src/__tests__`

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback4-example-shopping#68]
## Description

Follow the new file structure discussed in https://github.com/strongloop/loopback-next/pull/2283, move the `/test` folder to `src/__tests__`.

Reference PR: https://github.com/strongloop/loopback-next/pull/2316

## Acceptance Criteria

- [ ] Refactor the test files into `src/__tests__`

**Comment by dhmlau** [comment]
Fixed via https://github.com/strongloop/loopback4-example-shopping/pull/84
