### ISSUE TITLE
Add documentation for this example

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback4-example-shopping#69]
## Description

As a demo repository, let's add more documentation about the user scenarios and how to play with the app.

## Acceptance Criteria

Document:

- [ ] the models this example has and how they interact with each other
- [ ] services
- [ ] login system

**Comment by emonddr** [comment]
provide nice diagrams for the models involved

**Comment by dhmlau** [comment]
@emonddr, i believe this is very much related to your tutorial. https://github.com/strongloop/loopback-next/pull/3046
