### ISSUE TITLE
jwt-strategy.ts

### ISSUE THREAD

**Issue by heroca60** [strongloop/loopback4-example-shopping#724]
@bind(**asAuthStrategy**, asSpecEnhancer)

Argument of type 'BindingTemplate<unknown>' is not assignable to parameter of type 'BindingSpec'.

![Captura realizada el 2020-05-30 20 50 05](https://user-images.githubusercontent.com/16751287/83343412-2adc0a80-a2b7-11ea-8dad-94446522e7cf.png)

**Comment by raymondfeng** [comment]
Do you see this from a fresh checkout? If not, you seem to have multiple versions of the same module in the dependency tree. Please remove node_modules and run `npm i`. You can also use `lb4 update` to check versions.

**Comment by heroca60** [comment]
It is a development that I am running, previously I have already implemented it, but I do not understand why in this project I have the following bug.

**Comment by jannyHou** [comment]
@heroca60 I cloned the latest code and install&build, the code doesn't have error

<img width="642" alt="Screen Shot 2020-06-19 at 12 14 01 PM" src="https://user-images.githubusercontent.com/12554153/85155187-75053b80-b226-11ea-955a-63d8a1ac239a.png">

Can you provide more info about your environment? I think the best way is a fresh clone of the repo, then install and build the project again.

**Comment by dhmlau** [comment]
Closing as resolved.
