### ISSUE TITLE
Grpc server connect to Repository

### ISSUE THREAD

**Issue by Chenjigaram** [strongloop/loopback4-example-shopping#736]
Hi 
I am trying to connect from grpc service to repository, but its showing error 

import {repository} from '@loopback/repository';
import {TestRepository} from '../repositories';
export class TestService {

  @repository(TestRepository)
  private testRepository: TestRepository;

  constructor(){}

  getKey: handleUnaryCall<{id: string}, unknown> = (
      call,
      callback,
  ) => {
    let id = call.request.id || '';
    console.log(id);
    console.log(this.testRepository.findById(id));
    callback(null, {test: {} || {}});
  };

can someone help how I can reuse TestRepository here?

**Comment by jannyHou** [comment]
@raymondfeng could you help take a look? Thanks.

**Comment by jannyHou** [comment]
@Chenjigaram Could you provide more details of the error and also some sample of how you connect to the grpc service?

This example demos how to create and configure a grpc datasource as in [datasources/recommender-grpc.datasource.ts](https://github.com/strongloop/loopback4-example-shopping/blob/1949352e58c736873bbb4f027f5ea9f9303da25d/packages/shopping/src/datasources/recommender-grpc.datasource.ts)

and create a service connects to the datasource in [services/grpc.service.ts](https://github.com/strongloop/loopback4-example-shopping/blob/1949352e58c736873bbb4f027f5ea9f9303da25d/packages/shopping/src/services/recommender-grpc.service.ts)

**Comment by Chenjigaram** [comment]
Hi @jannyHou 

The issue is in Providing gRPC service 



```

import path from 'path';
import {
  loadPackageDefinition,
  GrpcObject,
  handleUnaryCall,
  Server,
  ServiceDefinition,
  ServerCredentials,
} from 'grpc';
import {repository} from '@loopback/repository';
import {TestRepository} from '../repositories';
import {loadSync} from '@grpc/proto-loader';

export const PROTO_PATH = path.join(
    __dirname,
    '../../protos/test.proto',
);

export function loadTestService() {
  const packageDefinition = loadSync(PROTO_PATH, {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true,
  });

  const pkg = loadPackageDefinition(packageDefinition);
  const test = (pkg.test as GrpcObject)
      .TestService as GrpcObject;
  return test;
}


export class TestService {

  @repository(TestRepository)
  private testRepository: TestRepository;

  constructor(){}

  getTest: handleUnaryCall<{id: string}, unknown> = (
      call,
      callback,
  ) => {
    let id = call.request.id || '';
    callback(null, {test: {id} || {}});
  };
}
/**
 * Get a new server with the handler functions in this file bound to the methods
 * it serves.
 * @return The new server object
 */
export function createGRPCTestServer(port = '0.0.0.0:50051') {
  const server = new Server();
  const test = loadTestService();
  const testService = new TestService();

  server.addService(test.service as ServiceDefinition<unknown>, {
    getTest:testService.getTest,
  });

  server.bind(port, ServerCredentials.createInsecure());
  return server;
}

export function grpcMain(port = '0.0.0.0:50051') {
  const testServer = createGRPCTestServer(port);
  testServer.start();
  console.log(`Test gRPC server is running at ${port}.`);
  return testServer;
}

if (require.main === module) {
  grpcMain();
}

```

In the TestService handler getTest method I want to use TestRepository to check whether id is present in database or not

**Comment by Chenjigaram** [comment]
Hi @jannyHou @raymondfeng 
Any luck in finding a way ?

**Comment by jannyHou** [comment]
Sorry for replying late, looking.

**Comment by mrmodise** [comment]
@Chenjigaram here to help. Correct me if am wrong the challenge you are having is using the TestRepository inside your service?

Looking at your code I think the issue is on the binding:

```typescript
@repository(TestRepository) // change to @repository('repositories.TestRepository')
  private testRepository: TestRepository;
```

**Comment by mrmodise** [comment]
@Chenjigaram is this issue still pending?

**Comment by mrmodise** [comment]
Closing the issue due to inactivity. Please feel free to open it again if needed. Thanks
