### ISSUE TITLE
Add password reset functionality

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback4-example-shopping#818]
Password reset functionality is a common requirement, let's add it in the example app. Ref: https://github.com/strongloop/loopback4-example-shopping/issues/456.

**Comment by mrmodise** [comment]
Will start work on this

**Comment by argupta23** [comment]
@hacksparrow @mrmodise @dhmlau 
Please see my comment in #456 

Based on my discussion with mrmodise what is implemented here is Change Password.

I think it might help to open another feature to track Password Reset / Forgot Password that implements what I have described. Thoughts and feedback are welcome.

Thanks
