### ISSUE TITLE
Update datasource config from JSON files to Typescript files

### ISSUE THREAD

**Issue by mrmodise** [strongloop/loopback4-example-shopping#879]
I would like to update the datasources in this example to follow the new config style of using TypeScript files, as per: https://github.com/strongloop/loopback-next/issues/5220

**Comment by bajtos** [comment]
@mrmodise Let's not create new issues for individual subtasks from strongloop/loopback-next#5220 please, to keep all discussions in a single place. Please go ahead and send a pull request instead 😄
