### ISSUE TITLE
Shopping App Website: use other hosts than localhost

### ISSUE THREAD

**Issue by johanschvn** [strongloop/loopback4-example-shopping#923]
The Shopping App Website does not work (e.g. no products are displayed) if you try to run it on other hosts than localhost. In packages/shopping/public/config.js  the base URL of the API is coded as `const apiUrl = 'http://localhost:3000';`. Changing it to `const apiUrl = location.protocol + '//' + location.hostname + (location.port ? ':' + location.port : '');` will make it work even if run on an other host or port.

**Comment by mrmodise** [comment]
Thanks for the issue. Can you give more insight into what you mean by other hosts please

**Comment by johanschvn** [comment]
@mrmodise 
e.g. if you deploy the application to a server called shoppy.example.com and start it on port 80 and call it from http://shoppy.example.com/ 
i.e. not running locally on port 3000 and accessing through http://localhost:3000/

**Comment by mrmodise** [comment]
Okay but that depends on how it's deployed. I think you will have to do the configs at server level to point https://shoppy.example.com to http://localhost:3000. Maybe instead we can add scripts to deploy to different environments instead e.g. AWS, IBM, Heroku. What do you think?

**Comment by johanschvn** [comment]
@mrmodise the code I want to have changed runs in the browser, not on the server; does not matter how it is deployed as long as you do not change the path part of the URL

**Comment by dougal83** [comment]
@johanschvn Would the [rest configuration](https://loopback.io/doc/en/lb4/Server.html#configuration) be something that resolve the issue?

**Comment by mrmodise** [comment]
> @mrmodise the code I want to have changed runs in the browser, not on the server; does not matter how it is deployed as long as you do not change the path part of the URL

aha! does this mean you coupled the UI and the backend?

**Comment by bajtos** [comment]
> `const apiUrl = 'http://localhost:3000';`. Changing it to `const apiUrl = location.protocol + '//' + location.hostname + (location.port ? ':' + location.port : '');` will make it work even if run on an other host or port.

Instead of building the URL manually, can we perhaps leverage `url` property of `RestServer`? See https://loopback.io/doc/en/lb4/apidocs.rest.restserver.url.html

```ts
const apiUrl = app.restServer.url;
```

**Comment by mrmodise** [comment]
@bajtos already using the built-in approach, see: https://github.com/strongloop/loopback4-example-shopping/blob/59472a5c1833a634c4fbf16ee60e0714eb448961/packages/shopping/src/index.ts#L16 

This is why i wanted to understand the use case a little bit more

**Comment by johanschvn** [comment]
@bajtos @mrmodis I do not think app.restServer.url is available in the browser. The code I propose changing is served as a static page from the public directory. As for as I can see no template engine is used; all pages are served as is. 
Also, I think app.restServer.url is the url as seen on the server; that is not necessarily the same as seen from the browser (it is not when I run the app on OpenShift).

**Comment by mrmodise** [comment]
Thanks makes sense. I usually prefer decoupled FE from BE so wont be the best person to advise but thanks for raising it. I will look into it

**Comment by johanschvn** [comment]
@mrmodise do you want me to prepare a PR?
