### ISSUE TITLE
Make it possible to select JWT secret via environment variable

### ISSUE THREAD

**Issue by johanschvn** [strongloop/loopback4-example-shopping#925]
I think it would be useful if the loopback4-example-shopping allowed setting the JWT secret via an environment variable.
Today the shopping API/application uses the default secret defined in @loopback/authentication-jwt.
I suggest adding code like this to setUpBindings() in packages/shopping/src/application.ts:
```
    let token = process.env.JWTSECRET;
    if (!token) {
      console.error('JWTSECRET not set, using default secret for JWT generation/validation');
    } else {
      this.bind(TokenServiceBindings.TOKEN_SECRET).to(token);
    }    
```
This code serves both as an example of how to use your own secret with @loopback/authentication-jwt and makes it possible to use loopback4-example-shopping in demos together with other JWT generators/validators.

**Comment by mrmodise** [comment]
Thanks for the suggestion. Do you mind putting together a PR for this? I think its a good idea

**Comment by johanschvn** [comment]
I am working on a PR now.
