### ISSUE TITLE
How to build and deploy loopback4-example-shopping on OpenShift Container Platform?

### ISSUE THREAD

**Issue by johanschvn** [strongloop/loopback4-example-shopping#935]
There is currently no instructions for building and deploying on OpenShift Container Platform.
I have start documenting how I do it in https://github.com/strongloop/loopback4-example-shopping/pull/934 .
Is there a better way?
Please comment here or in the PR!

**Comment by dhmlau** [comment]
@johanschvn, assigning this to you since you have a PR in progress. Thanks!

**Comment by johanschvn** [comment]
My PR is now ready for review.

**Comment by johanschvn** [comment]
After feedback from @mrmodise I have decided to add more info to README.md.
My intention is to write instructions for how to quickly get the application running on OpenShift for test and demo purpose rather than documenting production best practice.

**Comment by johanschvn** [comment]
Closing this as my PR has been merged. Instructions are now available in openshift/README.md.
